import type { StageData } from './types';

/**
 * The A1 curriculum: 8 stages, one per city on the map. Every German sentence
 * here was written by hand and is reused by the generator — fix it here and
 * re-seed to fix every derived question at once.
 */

const koeln: StageData = {
  cityName: 'Cologne', cityNameDe: 'Köln', emoji: '⛪',
  theme: 'Greetings & Introducing Yourself',
  grammarNote: 'German verbs change with the person: ich bin (I am), du bist (you are), er/sie ist (he/she is), wir sind (we are). "Ich heiße Anna" = "I am called Anna".',
  vocab: [
    { de: 'Hallo', en: 'hello', ex: 'Hallo, wie geht es dir?', exEn: 'Hello, how are you?' },
    { de: 'Tschüss', en: 'bye', ex: 'Tschüss, bis morgen!', exEn: 'Bye, see you tomorrow!' },
    { de: 'Guten Morgen', en: 'good morning', ex: 'Guten Morgen, Frau Schmidt!', exEn: 'Good morning, Mrs Schmidt!' },
    { de: 'Guten Tag', en: 'good day', ex: 'Guten Tag, wie kann ich helfen?', exEn: 'Good day, how can I help?' },
    { de: 'Guten Abend', en: 'good evening', ex: 'Guten Abend, Herr Müller!', exEn: 'Good evening, Mr Müller!' },
    { de: 'Gute Nacht', en: 'good night', ex: 'Gute Nacht, schlaf gut!', exEn: 'Good night, sleep well!' },
    { de: 'Auf Wiedersehen', en: 'goodbye', ex: 'Auf Wiedersehen und danke!', exEn: 'Goodbye and thank you!' },
    { de: 'danke', en: 'thank you', ex: 'Vielen Dank, das ist nett!', exEn: 'Many thanks, that is kind!' },
    { de: 'bitte', en: 'please / you are welcome', ex: 'Ein Wasser, bitte!', exEn: 'A water, please!' },
    { de: 'ja', en: 'yes', ex: 'Ja, das stimmt.', exEn: 'Yes, that is right.' },
    { de: 'nein', en: 'no', ex: 'Nein, danke.', exEn: 'No, thank you.' },
    { de: 'Entschuldigung', en: 'excuse me / sorry', ex: 'Entschuldigung, wo ist der Dom?', exEn: 'Excuse me, where is the cathedral?' },
    { de: 'Name', g: 'der', en: 'name', ex: 'Mein Name ist Anna.', exEn: 'My name is Anna.' },
    { de: 'Stadt', g: 'die', en: 'city', ex: 'Köln ist eine schöne Stadt.', exEn: 'Cologne is a beautiful city.' },
    { de: 'Land', g: 'das', en: 'country', ex: 'Deutschland ist ein großes Land.', exEn: 'Germany is a big country.' },
    { de: 'Freund', g: 'der', en: 'friend (male)', ex: 'Max ist mein Freund.', exEn: 'Max is my friend.' },
    { de: 'Freundin', g: 'die', en: 'friend (female)', ex: 'Meine Freundin wohnt in Köln.', exEn: 'My friend lives in Cologne.' },
    { de: 'heißen', en: 'to be called', ex: 'Wie heißen Sie?', exEn: 'What are you called?' },
    { de: 'kommen', en: 'to come', ex: 'Woher kommen Sie?', exEn: 'Where do you come from?' },
    { de: 'wohnen', en: 'to live', ex: 'Wo wohnen Sie?', exEn: 'Where do you live?' },
    { de: 'sprechen', en: 'to speak', ex: 'Sie sprechen gut Deutsch!', exEn: 'You speak German well!' },
    { de: 'lernen', en: 'to learn', ex: 'Wir lernen Deutsch.', exEn: 'We are learning German.' },
    { de: 'Dom', g: 'der', en: 'cathedral', ex: 'Der Dom in Köln ist berühmt.', exEn: 'The cathedral in Cologne is famous.' },
    { de: 'Sprache', g: 'die', en: 'language', ex: 'Deutsch ist eine schöne Sprache.', exEn: 'German is a beautiful language.' },
  ],
  grammar: [
    { en: 'I am Anna', de: 'Ich bin Anna' },
    { en: 'I am called Max', de: 'Ich heiße Max' },
    { en: 'I come from India', de: 'Ich komme aus Indien' },
    { en: 'I live in Cologne', de: 'Ich wohne in Köln' },
    { en: 'You are my friend', de: 'Du bist mein Freund' },
    { en: 'We are in Germany', de: 'Wir sind in Deutschland' },
    { en: 'She speaks German', de: 'Sie spricht Deutsch' },
    { en: 'How are you?', de: 'Wie geht es dir?' },
  ],
  errors: [
    { bad: 'Ich bist Anna.', wrong: 'bist', right: 'bin' },
    { bad: 'Du bin mein Freund.', wrong: 'bin', right: 'bist' },
    { bad: 'Wir ist in Köln.', wrong: 'ist', right: 'sind' },
    { bad: 'Ich heißen Max.', wrong: 'heißen', right: 'heiße' },
  ],
  reading: {
    passage: 'Hallo! Ich heiße Anna. Ich komme aus Deutschland und ich wohne in Köln. Köln ist eine schöne Stadt und der Dom ist sehr berühmt. Ich spreche Deutsch und Englisch. Mein Freund Max kommt aus Indien. Er lernt Deutsch.',
    qs: [
      { q: 'Where does Anna live?', options: ['Köln', 'Berlin', 'Indien'], a: 'Köln' },
      { q: 'Where does Max come from?', options: ['Deutschland', 'Indien', 'England'], a: 'Indien' },
      { q: 'What is famous in Cologne?', options: ['der Dom', 'die Bank', 'der Park'], a: 'der Dom' },
      { q: 'Which languages does Anna speak?', options: ['German and English', 'only German', 'German and Hindi'], a: 'German and English' },
      { q: 'What is Max doing?', options: ['He is learning German', 'He is working in Köln', 'He is visiting Anna'], a: 'He is learning German' },
    ],
  },
  speaking: [
    'Hallo! Wie geht es dir?',
    'Ich heiße Anna.',
    'Ich komme aus Indien.',
    'Guten Morgen!',
    'Auf Wiedersehen!',
    'Willkommen in Köln!',
  ],
  writing: [
    { prompt: 'Introduce yourself in three sentences: your name, where you come from, where you live.', hint: 'Ich heiße... Ich komme aus... Ich wohne in...' },
    { prompt: 'Greet someone in the morning and ask their name.', hint: 'Guten Morgen... Wie heißt du?' },
    { prompt: 'Say that German is a beautiful language and that you are learning it.', hint: 'Deutsch ist... Ich lerne...' },
  ],
};

const frankfurt: StageData = {
  cityName: 'Frankfurt', cityNameDe: 'Frankfurt', emoji: '🏦',
  theme: 'Numbers, Money & Shopping',
  grammarNote: '"haben" (to have): ich habe, du hast, er hat, wir haben. "kosten" (to cost): Das kostet zehn Euro. Euro never takes a plural -s: zehn Euro, not zehn Euros.',
  vocab: [
    { de: 'eins', en: 'one', ex: 'Ich habe nur eins.', exEn: 'I have only one.' },
    { de: 'zwei', en: 'two', ex: 'Zwei Kaffee, bitte!', exEn: 'Two coffees, please!' },
    { de: 'drei', en: 'three', ex: 'Wir sind drei Freunde.', exEn: 'We are three friends.' },
    { de: 'vier', en: 'four', ex: 'Das Zimmer hat vier Fenster.', exEn: 'The room has four windows.' },
    { de: 'fünf', en: 'five', ex: 'Das Brot kostet fünf Euro.', exEn: 'The bread costs five euros.' },
    { de: 'sechs', en: 'six', ex: 'Der Film beginnt um sechs.', exEn: 'The film starts at six.' },
    { de: 'sieben', en: 'seven', ex: 'Die Woche hat sieben Tage.', exEn: 'The week has seven days.' },
    { de: 'acht', en: 'eight', ex: 'Ich arbeite acht Stunden.', exEn: 'I work eight hours.' },
    { de: 'neun', en: 'nine', ex: 'Der Zug kommt um neun.', exEn: 'The train comes at nine.' },
    { de: 'zehn', en: 'ten', ex: 'Das kostet zehn Euro.', exEn: 'That costs ten euros.' },
    { de: 'hundert', en: 'one hundred', ex: 'Hundert Euro ist viel Geld.', exEn: 'A hundred euros is a lot of money.' },
    { de: 'Geld', g: 'das', en: 'money', ex: 'Ich habe kein Geld.', exEn: 'I have no money.' },
    { de: 'Euro', g: 'der', en: 'euro', ex: 'Ein Euro ist nicht viel.', exEn: 'One euro is not much.' },
    { de: 'kaufen', en: 'to buy', ex: 'Wir kaufen eine Tasche.', exEn: 'We are buying a bag.' },
    { de: 'kosten', en: 'to cost', ex: 'Was kosten die Schuhe?', exEn: 'What do the shoes cost?' },
    { de: 'teuer', en: 'expensive', ex: 'Das Auto ist sehr teuer.', exEn: 'The car is very expensive.' },
    { de: 'billig', en: 'cheap', ex: 'Der Markt ist billig.', exEn: 'The market is cheap.' },
    { de: 'Geschäft', g: 'das', en: 'shop', ex: 'Das Geschäft ist heute offen.', exEn: 'The shop is open today.' },
    { de: 'Markt', g: 'der', en: 'market', ex: 'Der Markt ist im Zentrum.', exEn: 'The market is in the centre.' },
    { de: 'Bank', g: 'die', en: 'bank', ex: 'Die Bank ist in Frankfurt.', exEn: 'The bank is in Frankfurt.' },
    { de: 'bezahlen', en: 'to pay', ex: 'Ich bezahle mit Karte.', exEn: 'I pay by card.' },
    { de: 'Preis', g: 'der', en: 'price', ex: 'Der Preis ist gut.', exEn: 'The price is good.' },
    { de: 'Tasche', g: 'die', en: 'bag', ex: 'Die Tasche kostet zwanzig Euro.', exEn: 'The bag costs twenty euros.' },
    { de: 'verkaufen', en: 'to sell', ex: 'Sie verkaufen Obst auf dem Markt.', exEn: 'They sell fruit at the market.' },
  ],
  grammar: [
    { en: 'I have ten euros', de: 'Ich habe zehn Euro' },
    { en: 'The book costs five euros', de: 'Das Buch kostet fünf Euro' },
    { en: 'I would like a bag', de: 'Ich möchte eine Tasche' },
    { en: 'How much does that cost?', de: 'Wie viel kostet das?' },
    { en: 'That is too expensive', de: 'Das ist zu teuer' },
    { en: 'We have money', de: 'Wir haben Geld' },
    { en: 'The market is big', de: 'Der Markt ist groß' },
    { en: 'I pay by card', de: 'Ich bezahle mit Karte' },
  ],
  errors: [
    { bad: 'Ich habe zehn Euros.', wrong: 'Euros', right: 'Euro' },
    { bad: 'Das Buch kosten fünf Euro.', wrong: 'kosten', right: 'kostet' },
    { bad: 'Ich möchten eine Tasche.', wrong: 'möchten', right: 'möchte' },
    { bad: 'Du habe kein Geld.', wrong: 'habe', right: 'hast' },
  ],
  reading: {
    passage: 'Lena ist in Frankfurt. Sie geht zum Markt und kauft eine Tasche. Die Tasche kostet zwanzig Euro — das ist billig! Dann geht sie zur Bank. Frankfurt hat viele Banken. Am Abend hat Lena kein Geld mehr.',
    qs: [
      { q: 'What does Lena buy?', options: ['eine Tasche', 'ein Buch', 'Schuhe'], a: 'eine Tasche' },
      { q: 'How much does it cost?', options: ['zwanzig Euro', 'zehn Euro', 'hundert Euro'], a: 'zwanzig Euro' },
      { q: 'Was the bag cheap or expensive?', options: ['billig', 'teuer', 'neu'], a: 'billig' },
      { q: 'What does Frankfurt have many of?', options: ['Banken', 'Dome', 'Parks'], a: 'Banken' },
      { q: 'What does Lena have in the evening?', options: ['kein Geld', 'viel Geld', 'eine neue Tasche'], a: 'kein Geld' },
    ],
  },
  speaking: [
    'Wie viel kostet das?',
    'Das ist zu teuer!',
    'Ich möchte eine Tasche.',
    'Ich bezahle mit Karte.',
    'Der Preis ist gut.',
    'Zwei Kaffee, bitte!',
  ],
  writing: [
    { prompt: 'You are at the market. Ask the price of a bag and say it is too expensive.', hint: 'Wie viel kostet... Das ist zu...' },
    { prompt: 'Write two sentences about what you are buying and how you pay.', hint: 'Ich kaufe... Ich bezahle mit...' },
    { prompt: 'Count from one to five in German in a sentence.', hint: 'eins, zwei, drei...' },
  ],
};

const stuttgart: StageData = {
  cityName: 'Stuttgart', cityNameDe: 'Stuttgart', emoji: '🚗',
  theme: 'Family & People',
  grammarNote: 'Possessives match the noun\'s gender: mein Vater (der), meine Mutter (die), mein Kind (das). After "haben" masculine nouns take -en: Ich habe einen Bruder.',
  vocab: [
    { de: 'Familie', g: 'die', en: 'family', ex: 'Meine Familie wohnt in Stuttgart.', exEn: 'My family lives in Stuttgart.' },
    { de: 'Vater', g: 'der', en: 'father', ex: 'Mein Vater arbeitet viel.', exEn: 'My father works a lot.' },
    { de: 'Mutter', g: 'die', en: 'mother', ex: 'Meine Mutter kocht gern.', exEn: 'My mother likes cooking.' },
    { de: 'Bruder', g: 'der', en: 'brother', ex: 'Ich habe einen Bruder.', exEn: 'I have a brother.' },
    { de: 'Schwester', g: 'die', en: 'sister', ex: 'Meine Schwester ist jung.', exEn: 'My sister is young.' },
    { de: 'Sohn', g: 'der', en: 'son', ex: 'Der Sohn heißt Paul.', exEn: 'The son is called Paul.' },
    { de: 'Tochter', g: 'die', en: 'daughter', ex: 'Die Tochter lernt Deutsch.', exEn: 'The daughter is learning German.' },
    { de: 'Eltern', en: 'parents', ex: 'Meine Eltern sind zu Hause.', exEn: 'My parents are at home.' },
    { de: 'Kind', g: 'das', en: 'child', ex: 'Das Kind spielt im Park.', exEn: 'The child is playing in the park.' },
    { de: 'Mann', g: 'der', en: 'man / husband', ex: 'Der Mann heißt Thomas.', exEn: 'The man is called Thomas.' },
    { de: 'Frau', g: 'die', en: 'woman / wife', ex: 'Die Frau kommt aus Stuttgart.', exEn: 'The woman comes from Stuttgart.' },
    { de: 'Junge', g: 'der', en: 'boy', ex: 'Der Junge ist mein Sohn.', exEn: 'The boy is my son.' },
    { de: 'Mädchen', g: 'das', en: 'girl', ex: 'Das Mädchen liest ein Buch.', exEn: 'The girl is reading a book.' },
    { de: 'Großmutter', g: 'die', en: 'grandmother', ex: 'Meine Großmutter ist achtzig.', exEn: 'My grandmother is eighty.' },
    { de: 'Großvater', g: 'der', en: 'grandfather', ex: 'Mein Großvater erzählt Geschichten.', exEn: 'My grandfather tells stories.' },
    { de: 'alt', en: 'old', ex: 'Mein Vater ist fünfzig Jahre alt.', exEn: 'My father is fifty years old.' },
    { de: 'jung', en: 'young', ex: 'Meine Schwester ist noch jung.', exEn: 'My sister is still young.' },
    { de: 'groß', en: 'big / tall', ex: 'Mein Bruder ist sehr groß.', exEn: 'My brother is very tall.' },
    { de: 'klein', en: 'small / short', ex: 'Das Kind ist noch klein.', exEn: 'The child is still small.' },
    { de: 'lieben', en: 'to love', ex: 'Wir lieben unsere Familie.', exEn: 'We love our family.' },
    { de: 'Leute', en: 'people', ex: 'Die Leute in Stuttgart sind nett.', exEn: 'The people in Stuttgart are nice.' },
    { de: 'wohnen', en: 'to live (reside)', ex: 'Meine Eltern wohnen hier.', exEn: 'My parents live here.' },
    { de: 'zusammen', en: 'together', ex: 'Wir wohnen zusammen.', exEn: 'We live together.' },
    { de: 'nett', en: 'nice / kind', ex: 'Meine Großmutter ist sehr nett.', exEn: 'My grandmother is very kind.' },
  ],
  grammar: [
    { en: 'My father is old', de: 'Mein Vater ist alt' },
    { en: 'I have a sister', de: 'Ich habe eine Schwester' },
    { en: 'I have a brother', de: 'Ich habe einen Bruder' },
    { en: 'My family is big', de: 'Meine Familie ist groß' },
    { en: 'His brother is small', de: 'Sein Bruder ist klein' },
    { en: 'Her mother is young', de: 'Ihre Mutter ist jung' },
    { en: 'We love our family', de: 'Wir lieben unsere Familie' },
    { en: 'Do you have children?', de: 'Hast du Kinder?' },
  ],
  errors: [
    { bad: 'Mein Mutter ist jung.', wrong: 'Mein', right: 'Meine' },
    { bad: 'Ich habe ein Bruder.', wrong: 'ein', right: 'einen' },
    { bad: 'Das Kind spielen im Park.', wrong: 'spielen', right: 'spielt' },
    { bad: 'Meine Vater arbeitet viel.', wrong: 'Meine', right: 'Mein' },
  ],
  reading: {
    passage: 'Das ist meine Familie. Mein Vater heißt Thomas und meine Mutter heißt Maria. Ich habe einen Bruder und eine Schwester. Mein Bruder ist groß, aber meine Schwester ist noch klein. Wir wohnen zusammen in Stuttgart. Meine Großmutter wohnt auch hier. Sie ist alt, aber sehr nett.',
    qs: [
      { q: 'What is the father called?', options: ['Thomas', 'Paul', 'Max'], a: 'Thomas' },
      { q: 'How many siblings does the writer have?', options: ['zwei', 'eins', 'drei'], a: 'zwei' },
      { q: 'What is the sister like?', options: ['klein', 'groß', 'alt'], a: 'klein' },
      { q: 'Where does the family live?', options: ['Stuttgart', 'Köln', 'Frankfurt'], a: 'Stuttgart' },
      { q: 'What is the grandmother like?', options: ['alt, aber nett', 'jung und groß', 'klein und laut'], a: 'alt, aber nett' },
    ],
  },
  speaking: [
    'Das ist meine Familie.',
    'Ich habe einen Bruder.',
    'Meine Mutter heißt Maria.',
    'Mein Vater ist groß.',
    'Wir wohnen zusammen.',
    'Meine Großmutter ist nett.',
  ],
  writing: [
    { prompt: 'Describe your family in three sentences.', hint: 'Meine Familie ist... Ich habe... Mein Vater heißt...' },
    { prompt: 'Write about one family member: name and one adjective.', hint: 'Meine Schwester heißt... Sie ist...' },
    { prompt: 'Say who you live with.', hint: 'Ich wohne mit... zusammen' },
  ],
};

const muenchen: StageData = {
  cityName: 'Munich', cityNameDe: 'München', emoji: '🍺',
  theme: 'Food & Drink',
  grammarNote: '"essen" (to eat) is irregular: ich esse, du isst, er isst. "trinken" is regular: ich trinke, du trinkst. To order politely say "Ich möchte... bitte" or "Ich hätte gern...".',
  vocab: [
    { de: 'Essen', g: 'das', en: 'food', ex: 'Das Essen schmeckt lecker.', exEn: 'The food tastes delicious.' },
    { de: 'Brot', g: 'das', en: 'bread', ex: 'Ich esse Brot mit Käse.', exEn: 'I eat bread with cheese.' },
    { de: 'Käse', g: 'der', en: 'cheese', ex: 'Der Käse kommt aus Bayern.', exEn: 'The cheese comes from Bavaria.' },
    { de: 'Butter', g: 'die', en: 'butter', ex: 'Die Butter ist frisch.', exEn: 'The butter is fresh.' },
    { de: 'Wasser', g: 'das', en: 'water', ex: 'Ein Wasser ohne Eis, bitte.', exEn: 'A water without ice, please.' },
    { de: 'Milch', g: 'die', en: 'milk', ex: 'Die Milch ist kalt.', exEn: 'The milk is cold.' },
    { de: 'Kaffee', g: 'der', en: 'coffee', ex: 'Der Kaffee ist heiß.', exEn: 'The coffee is hot.' },
    { de: 'Tee', g: 'der', en: 'tea', ex: 'Ich trinke Tee am Abend.', exEn: 'I drink tea in the evening.' },
    { de: 'Bier', g: 'das', en: 'beer', ex: 'Das Bier in München ist berühmt.', exEn: 'The beer in Munich is famous.' },
    { de: 'Wein', g: 'der', en: 'wine', ex: 'Der Wein kommt aus Frankreich.', exEn: 'The wine comes from France.' },
    { de: 'Apfel', g: 'der', en: 'apple', ex: 'Der Apfel ist rot und süß.', exEn: 'The apple is red and sweet.' },
    { de: 'Wurst', g: 'die', en: 'sausage', ex: 'Die Wurst schmeckt gut.', exEn: 'The sausage tastes good.' },
    { de: 'essen', en: 'to eat', ex: 'Was möchtest du essen?', exEn: 'What would you like to eat?' },
    { de: 'trinken', en: 'to drink', ex: 'Was möchtest du trinken?', exEn: 'What would you like to drink?' },
    { de: 'Frühstück', g: 'das', en: 'breakfast', ex: 'Das Frühstück ist um acht.', exEn: 'Breakfast is at eight.' },
    { de: 'Restaurant', g: 'das', en: 'restaurant', ex: 'Das Restaurant ist voll.', exEn: 'The restaurant is full.' },
    { de: 'Kellner', g: 'der', en: 'waiter', ex: 'Der Kellner bringt die Speisekarte.', exEn: 'The waiter brings the menu.' },
    { de: 'Speisekarte', g: 'die', en: 'menu', ex: 'Die Speisekarte, bitte!', exEn: 'The menu, please!' },
    { de: 'schmecken', en: 'to taste', ex: 'Wie schmecken die Äpfel?', exEn: 'How do the apples taste?' },
    { de: 'lecker', en: 'delicious', ex: 'Die Suppe ist sehr lecker.', exEn: 'The soup is very delicious.' },
    { de: 'hungrig', en: 'hungry', ex: 'Ich bin sehr hungrig.', exEn: 'I am very hungry.' },
    { de: 'durstig', en: 'thirsty', ex: 'Bist du durstig?', exEn: 'Are you thirsty?' },
    { de: 'bestellen', en: 'to order', ex: 'Wir bestellen zwei Bier.', exEn: 'We order two beers.' },
    { de: 'Rechnung', g: 'die', en: 'bill', ex: 'Die Rechnung, bitte!', exEn: 'The bill, please!' },
  ],
  grammar: [
    { en: 'I eat bread', de: 'Ich esse Brot' },
    { en: 'He drinks coffee', de: 'Er trinkt Kaffee' },
    { en: 'We eat in the restaurant', de: 'Wir essen im Restaurant' },
    { en: 'The food tastes good', de: 'Das Essen schmeckt gut' },
    { en: 'I would like a beer, please', de: 'Ich möchte ein Bier, bitte' },
    { en: 'The bill, please', de: 'Die Rechnung, bitte' },
    { en: 'Are you hungry?', de: 'Bist du hungrig?' },
    { en: 'I drink water every day', de: 'Ich trinke jeden Tag Wasser' },
  ],
  errors: [
    { bad: 'Er trinke Kaffee.', wrong: 'trinke', right: 'trinkt' },
    { bad: 'Ich esst Brot.', wrong: 'esst', right: 'esse' },
    { bad: 'Das Essen schmecken gut.', wrong: 'schmecken', right: 'schmeckt' },
    { bad: 'Du bist hungrig?', wrong: 'Du', right: 'Bist' },
  ],
  reading: {
    passage: 'Paul ist in München. Er ist hungrig und geht in ein Restaurant. Der Kellner bringt die Speisekarte. Paul bestellt eine Wurst mit Brot und ein Bier. Das Essen schmeckt sehr lecker. Am Ende sagt Paul: "Die Rechnung, bitte!" Alles kostet zwölf Euro.',
    qs: [
      { q: 'Why does Paul go to a restaurant?', options: ['Er ist hungrig', 'Er ist müde', 'Er arbeitet dort'], a: 'Er ist hungrig' },
      { q: 'What does the waiter bring?', options: ['die Speisekarte', 'die Rechnung', 'einen Kaffee'], a: 'die Speisekarte' },
      { q: 'What does Paul order?', options: ['Wurst, Brot und Bier', 'Käse und Wein', 'Kaffee und Kuchen'], a: 'Wurst, Brot und Bier' },
      { q: 'How does the food taste?', options: ['sehr lecker', 'nicht gut', 'zu kalt'], a: 'sehr lecker' },
      { q: 'How much does everything cost?', options: ['zwölf Euro', 'zwanzig Euro', 'zehn Euro'], a: 'zwölf Euro' },
    ],
  },
  speaking: [
    'Ich bin hungrig.',
    'Die Speisekarte, bitte!',
    'Ich möchte ein Bier, bitte.',
    'Das schmeckt lecker!',
    'Die Rechnung, bitte!',
    'Was möchtest du trinken?',
  ],
  writing: [
    { prompt: 'Order food and a drink politely in a restaurant.', hint: 'Ich möchte... und... bitte' },
    { prompt: 'Write what you eat for breakfast.', hint: 'Zum Frühstück esse ich... Ich trinke...' },
    { prompt: 'Say the food is delicious and ask for the bill.', hint: 'Das Essen ist... Die Rechnung...' },
  ],
};

const duesseldorf: StageData = {
  cityName: 'Düsseldorf', cityNameDe: 'Düsseldorf', emoji: '🎨',
  theme: 'Daily Routine & Time',
  grammarNote: 'Time: "Wie spät ist es?" — "Es ist zehn Uhr." Separable verbs split: aufstehen → Ich stehe um sieben auf. Frequency words: immer (always), oft (often), nie (never).',
  vocab: [
    { de: 'Zeit', g: 'die', en: 'time', ex: 'Ich habe keine Zeit.', exEn: 'I have no time.' },
    { de: 'Uhr', g: 'die', en: 'clock / o\'clock', ex: 'Es ist acht Uhr.', exEn: 'It is eight o\'clock.' },
    { de: 'Tag', g: 'der', en: 'day', ex: 'Heute ist ein schöner Tag.', exEn: 'Today is a beautiful day.' },
    { de: 'Woche', g: 'die', en: 'week', ex: 'Die Woche beginnt am Montag.', exEn: 'The week starts on Monday.' },
    { de: 'Morgen', g: 'der', en: 'morning', ex: 'Der Morgen ist ruhig.', exEn: 'The morning is quiet.' },
    { de: 'Abend', g: 'der', en: 'evening', ex: 'Am Abend sehe ich fern.', exEn: 'In the evening I watch TV.' },
    { de: 'Nacht', g: 'die', en: 'night', ex: 'Die Nacht ist lang.', exEn: 'The night is long.' },
    { de: 'heute', en: 'today', ex: 'Heute lerne ich Deutsch.', exEn: 'Today I am learning German.' },
    { de: 'morgen', en: 'tomorrow', ex: 'Bis morgen!', exEn: 'See you tomorrow!' },
    { de: 'gestern', en: 'yesterday', ex: 'Gestern war Sonntag.', exEn: 'Yesterday was Sunday.' },
    { de: 'jetzt', en: 'now', ex: 'Was machst du jetzt?', exEn: 'What are you doing now?' },
    { de: 'früh', en: 'early', ex: 'Ich stehe sehr früh auf.', exEn: 'I get up very early.' },
    { de: 'spät', en: 'late', ex: 'Wie spät ist es?', exEn: 'How late is it? (What time is it?)' },
    { de: 'aufstehen', en: 'to get up', ex: 'Ich muss um sechs aufstehen.', exEn: 'I have to get up at six.' },
    { de: 'arbeiten', en: 'to work', ex: 'Wir arbeiten jeden Tag.', exEn: 'We work every day.' },
    { de: 'schlafen', en: 'to sleep', ex: 'Ich möchte lange schlafen.', exEn: 'I would like to sleep long.' },
    { de: 'Arbeit', g: 'die', en: 'work / job', ex: 'Die Arbeit beginnt um neun.', exEn: 'Work starts at nine.' },
    { de: 'Schule', g: 'die', en: 'school', ex: 'Die Schule ist um eins fertig.', exEn: 'School finishes at one.' },
    { de: 'gehen', en: 'to go', ex: 'Wir gehen jetzt nach Hause.', exEn: 'We are going home now.' },
    { de: 'machen', en: 'to do / make', ex: 'Was machen wir heute?', exEn: 'What are we doing today?' },
    { de: 'immer', en: 'always', ex: 'Ich trinke immer Kaffee.', exEn: 'I always drink coffee.' },
    { de: 'oft', en: 'often', ex: 'Er ist oft müde.', exEn: 'He is often tired.' },
    { de: 'nie', en: 'never', ex: 'Sie ist nie spät.', exEn: 'She is never late.' },
    { de: 'Wochenende', g: 'das', en: 'weekend', ex: 'Am Wochenende schlafe ich lange.', exEn: 'On the weekend I sleep long.' },
  ],
  grammar: [
    { en: 'What time is it?', de: 'Wie spät ist es?' },
    { en: 'It is ten o\'clock', de: 'Es ist zehn Uhr' },
    { en: 'I get up at seven', de: 'Ich stehe um sieben auf' },
    { en: 'I work every day', de: 'Ich arbeite jeden Tag' },
    { en: 'Today I am going to school', de: 'Heute gehe ich zur Schule' },
    { en: 'I never work at night', de: 'Ich arbeite nie in der Nacht' },
    { en: 'What are you doing now?', de: 'Was machst du jetzt?' },
    { en: 'On the weekend I sleep long', de: 'Am Wochenende schlafe ich lange' },
  ],
  errors: [
    { bad: 'Wie spät ist er?', wrong: 'er', right: 'es' },
    { bad: 'Ich gehen zur Schule.', wrong: 'gehen', right: 'gehe' },
    { bad: 'Es ist zehn Uhren.', wrong: 'Uhren', right: 'Uhr' },
    { bad: 'Sie arbeitet nie nicht.', wrong: 'nicht', right: 'nie' },
  ],
  reading: {
    passage: 'Mein Tag beginnt früh. Ich stehe um sechs Uhr auf und trinke Kaffee. Um acht gehe ich zur Arbeit. Die Arbeit ist oft lang. Am Abend esse ich mit meiner Familie. Um elf Uhr schlafe ich. Am Wochenende stehe ich spät auf — das ist schön!',
    qs: [
      { q: 'When does the writer get up?', options: ['um sechs Uhr', 'um acht Uhr', 'um elf Uhr'], a: 'um sechs Uhr' },
      { q: 'What does the writer drink in the morning?', options: ['Kaffee', 'Tee', 'Milch'], a: 'Kaffee' },
      { q: 'When does work start?', options: ['um acht', 'um sechs', 'um neun'], a: 'um acht' },
      { q: 'Who does the writer eat with in the evening?', options: ['mit der Familie', 'mit Freunden', 'allein'], a: 'mit der Familie' },
      { q: 'What happens on the weekend?', options: ['spät aufstehen', 'früh arbeiten', 'zur Schule gehen'], a: 'spät aufstehen' },
    ],
  },
  speaking: [
    'Wie spät ist es?',
    'Es ist zehn Uhr.',
    'Ich stehe früh auf.',
    'Ich habe keine Zeit.',
    'Bis morgen!',
    'Was machst du jetzt?',
  ],
  writing: [
    { prompt: 'Describe your morning in three sentences.', hint: 'Ich stehe um... auf. Ich trinke... Dann gehe ich...' },
    { prompt: 'Write what you do on the weekend.', hint: 'Am Wochenende... Ich schlafe...' },
    { prompt: 'Say what time it is and where you are going.', hint: 'Es ist... Uhr. Ich gehe...' },
  ],
};

const hannover: StageData = {
  cityName: 'Hannover', cityNameDe: 'Hannover', emoji: '🌳',
  theme: 'City, Directions & Transport',
  grammarNote: 'Asking the way: "Wo ist...?" Directions: links (left), rechts (right), geradeaus (straight ahead). "nehmen" with masculine nouns: Ich nehme den Bus. Travel: Wir fahren nach Hannover.',
  vocab: [
    { de: 'Bahnhof', g: 'der', en: 'train station', ex: 'Der Bahnhof ist im Zentrum.', exEn: 'The station is in the centre.' },
    { de: 'Zug', g: 'der', en: 'train', ex: 'Der Zug kommt um neun.', exEn: 'The train comes at nine.' },
    { de: 'Bus', g: 'der', en: 'bus', ex: 'Ich nehme den Bus.', exEn: 'I take the bus.' },
    { de: 'Auto', g: 'das', en: 'car', ex: 'Das Auto ist neu.', exEn: 'The car is new.' },
    { de: 'Straße', g: 'die', en: 'street', ex: 'Die Straße ist lang.', exEn: 'The street is long.' },
    { de: 'links', en: 'left', ex: 'Das Hotel ist links.', exEn: 'The hotel is on the left.' },
    { de: 'rechts', en: 'right', ex: 'Die Bank ist rechts.', exEn: 'The bank is on the right.' },
    { de: 'geradeaus', en: 'straight ahead', ex: 'Gehen Sie geradeaus!', exEn: 'Go straight ahead!' },
    { de: 'Haltestelle', g: 'die', en: 'bus stop', ex: 'Wo ist die Haltestelle?', exEn: 'Where is the bus stop?' },
    { de: 'Ticket', g: 'das', en: 'ticket', ex: 'Das Ticket kostet drei Euro.', exEn: 'The ticket costs three euros.' },
    { de: 'fahren', en: 'to drive / travel', ex: 'Wir fahren mit dem Zug.', exEn: 'We travel by train.' },
    { de: 'Flughafen', g: 'der', en: 'airport', ex: 'Der Flughafen ist weit.', exEn: 'The airport is far.' },
    { de: 'Hotel', g: 'das', en: 'hotel', ex: 'Das Hotel hat hundert Zimmer.', exEn: 'The hotel has a hundred rooms.' },
    { de: 'Park', g: 'der', en: 'park', ex: 'Der Park ist sehr schön.', exEn: 'The park is very beautiful.' },
    { de: 'Kirche', g: 'die', en: 'church', ex: 'Die Kirche ist alt.', exEn: 'The church is old.' },
    { de: 'Museum', g: 'das', en: 'museum', ex: 'Das Museum ist heute offen.', exEn: 'The museum is open today.' },
    { de: 'weit', en: 'far', ex: 'Ist es weit von hier?', exEn: 'Is it far from here?' },
    { de: 'nah', en: 'near', ex: 'Der Bahnhof ist ganz nah.', exEn: 'The station is very near.' },
    { de: 'finden', en: 'to find', ex: 'Ich kann das Hotel nicht finden.', exEn: 'I cannot find the hotel.' },
    { de: 'fragen', en: 'to ask', ex: 'Wir fragen einen Mann.', exEn: 'We ask a man.' },
    { de: 'Karte', g: 'die', en: 'map / card', ex: 'Die Karte hilft uns.', exEn: 'The map helps us.' },
    { de: 'Weg', g: 'der', en: 'way / path', ex: 'Der Weg ist nicht weit.', exEn: 'The way is not far.' },
    { de: 'nehmen', en: 'to take', ex: 'Welchen Bus soll ich nehmen?', exEn: 'Which bus should I take?' },
    { de: 'Zentrum', g: 'das', en: 'centre', ex: 'Das Zentrum ist voll.', exEn: 'The centre is crowded.' },
  ],
  grammar: [
    { en: 'Where is the train station?', de: 'Wo ist der Bahnhof?' },
    { en: 'Go straight ahead', de: 'Gehen Sie geradeaus' },
    { en: 'The hotel is on the left', de: 'Das Hotel ist links' },
    { en: 'I am taking the bus', de: 'Ich nehme den Bus' },
    { en: 'We are travelling to Hannover', de: 'Wir fahren nach Hannover' },
    { en: 'Is it far?', de: 'Ist es weit?' },
    { en: 'The museum is very near', de: 'Das Museum ist ganz nah' },
    { en: 'How do I find the hotel?', de: 'Wie finde ich das Hotel?' },
  ],
  errors: [
    { bad: 'Wo ist die Bahnhof?', wrong: 'die', right: 'der' },
    { bad: 'Ich nehme der Bus.', wrong: 'der', right: 'den' },
    { bad: 'Wir fahrt nach Hannover.', wrong: 'fahrt', right: 'fahren' },
    { bad: 'Das Hotel ist auf links.', wrong: 'auf', right: 'ist' },
  ],
  reading: {
    passage: 'Ein Tourist ist in Hannover. Er fragt eine Frau: "Entschuldigung, wo ist das Museum?" Die Frau sagt: "Gehen Sie geradeaus und dann links. Das Museum ist neben dem Park. Es ist nicht weit." Der Tourist nimmt den Bus und findet das Museum. Das Ticket kostet fünf Euro.',
    qs: [
      { q: 'What is the tourist looking for?', options: ['das Museum', 'den Bahnhof', 'das Hotel'], a: 'das Museum' },
      { q: 'Which direction should he go?', options: ['geradeaus und dann links', 'rechts und dann links', 'nur rechts'], a: 'geradeaus und dann links' },
      { q: 'What is the museum next to?', options: ['dem Park', 'der Kirche', 'der Bank'], a: 'dem Park' },
      { q: 'How does the tourist travel?', options: ['mit dem Bus', 'mit dem Zug', 'mit dem Auto'], a: 'mit dem Bus' },
      { q: 'How much is the ticket?', options: ['fünf Euro', 'drei Euro', 'zehn Euro'], a: 'fünf Euro' },
    ],
  },
  speaking: [
    'Entschuldigung, wo ist der Bahnhof?',
    'Gehen Sie geradeaus!',
    'Das Hotel ist links.',
    'Ich nehme den Bus.',
    'Ist es weit von hier?',
    'Wir fahren nach Hannover.',
  ],
  writing: [
    { prompt: 'Give someone directions to the station: straight, then right.', hint: 'Gehen Sie... dann...' },
    { prompt: 'Write how you travel to school or work.', hint: 'Ich fahre mit dem... Ich nehme...' },
    { prompt: 'Ask politely where the museum is and if it is far.', hint: 'Entschuldigung, wo... Ist es...' },
  ],
};

const hamburg: StageData = {
  cityName: 'Hamburg', cityNameDe: 'Hamburg', emoji: '🚢',
  theme: 'Weather, Hobbies & Free Time',
  grammarNote: 'Weather uses "es": Es regnet (it rains), Es ist kalt. Likes with "gern": Ich spiele gern Fußball (I like playing football). Modal "können": Ich kann schwimmen (I can swim).',
  vocab: [
    { de: 'Wetter', g: 'das', en: 'weather', ex: 'Das Wetter ist heute gut.', exEn: 'The weather is good today.' },
    { de: 'Sonne', g: 'die', en: 'sun', ex: 'Die Sonne scheint heute.', exEn: 'The sun is shining today.' },
    { de: 'Regen', g: 'der', en: 'rain', ex: 'Der Regen ist kalt.', exEn: 'The rain is cold.' },
    { de: 'Schnee', g: 'der', en: 'snow', ex: 'Der Schnee ist weiß.', exEn: 'The snow is white.' },
    { de: 'Wind', g: 'der', en: 'wind', ex: 'Der Wind in Hamburg ist stark.', exEn: 'The wind in Hamburg is strong.' },
    { de: 'warm', en: 'warm', ex: 'Der Sommer ist warm.', exEn: 'The summer is warm.' },
    { de: 'kalt', en: 'cold', ex: 'Im Winter ist es kalt.', exEn: 'In winter it is cold.' },
    { de: 'scheinen', en: 'to shine', ex: 'Die Sonne kann morgen scheinen.', exEn: 'The sun may shine tomorrow.' },
    { de: 'regnen', en: 'to rain', ex: 'Es kann heute regnen.', exEn: 'It may rain today.' },
    { de: 'Hobby', g: 'das', en: 'hobby', ex: 'Mein Hobby ist Musik.', exEn: 'My hobby is music.' },
    { de: 'spielen', en: 'to play', ex: 'Die Kinder spielen im Park.', exEn: 'The children are playing in the park.' },
    { de: 'lesen', en: 'to read', ex: 'Ich möchte ein Buch lesen.', exEn: 'I would like to read a book.' },
    { de: 'schwimmen', en: 'to swim', ex: 'Ich kann gut schwimmen.', exEn: 'I can swim well.' },
    { de: 'tanzen', en: 'to dance', ex: 'Kannst du tanzen?', exEn: 'Can you dance?' },
    { de: 'Musik', g: 'die', en: 'music', ex: 'Die Musik ist laut.', exEn: 'The music is loud.' },
    { de: 'Sport', g: 'der', en: 'sport', ex: 'Sport ist gesund.', exEn: 'Sport is healthy.' },
    { de: 'Fußball', g: 'der', en: 'football', ex: 'Wir spielen gern Fußball.', exEn: 'We like playing football.' },
    { de: 'Buch', g: 'das', en: 'book', ex: 'Das Buch ist interessant.', exEn: 'The book is interesting.' },
    { de: 'Film', g: 'der', en: 'film', ex: 'Der Film beginnt um acht.', exEn: 'The film starts at eight.' },
    { de: 'sehen', en: 'to see / watch', ex: 'Ich will einen Film sehen.', exEn: 'I want to watch a film.' },
    { de: 'hören', en: 'to hear / listen', ex: 'Ich kann Musik hören.', exEn: 'I can listen to music.' },
    { de: 'Meer', g: 'das', en: 'sea', ex: 'Das Meer ist nicht weit.', exEn: 'The sea is not far.' },
    { de: 'Sommer', g: 'der', en: 'summer', ex: 'Im Sommer schwimmen wir viel.', exEn: 'In summer we swim a lot.' },
    { de: 'Winter', g: 'der', en: 'winter', ex: 'Der Winter in Hamburg ist kalt.', exEn: 'The winter in Hamburg is cold.' },
  ],
  grammar: [
    { en: 'The sun is shining', de: 'Die Sonne scheint' },
    { en: 'It is raining today', de: 'Es regnet heute' },
    { en: 'In winter it is cold', de: 'Im Winter ist es kalt' },
    { en: 'I play football', de: 'Ich spiele Fußball' },
    { en: 'I like listening to music', de: 'Ich höre gern Musik' },
    { en: 'We swim in the sea', de: 'Wir schwimmen im Meer' },
    { en: 'I am watching a film', de: 'Ich sehe einen Film' },
    { en: 'Can you dance?', de: 'Kannst du tanzen?' },
  ],
  errors: [
    { bad: 'Die Sonne scheinen.', wrong: 'scheinen', right: 'scheint' },
    { bad: 'Ich spielst Fußball.', wrong: 'spielst', right: 'spiele' },
    { bad: 'Wir schwimmt im Meer.', wrong: 'schwimmt', right: 'schwimmen' },
    { bad: 'Es regnet kalt.', wrong: 'kalt', right: 'heute' },
  ],
  reading: {
    passage: 'Hamburg liegt im Norden. Das Wetter ist oft kalt und der Wind ist stark. Aber die Stadt ist schön! Am Wochenende spiele ich Fußball im Park. Mein Freund liest gern Bücher und hört Musik. Im Sommer schwimmen wir im See. Im Winter sehen wir Filme zu Hause.',
    qs: [
      { q: 'What is the weather often like in Hamburg?', options: ['kalt und windig', 'warm und sonnig', 'heiß'], a: 'kalt und windig' },
      { q: 'What does the writer do on the weekend?', options: ['Fußball spielen', 'Bücher lesen', 'tanzen'], a: 'Fußball spielen' },
      { q: 'What does the friend like doing?', options: ['lesen und Musik hören', 'schwimmen und tanzen', 'Filme sehen'], a: 'lesen und Musik hören' },
      { q: 'What do they do in summer?', options: ['im See schwimmen', 'Filme sehen', 'Schnee sehen'], a: 'im See schwimmen' },
      { q: 'What do they do in winter?', options: ['Filme sehen', 'im Meer schwimmen', 'Fußball spielen'], a: 'Filme sehen' },
    ],
  },
  speaking: [
    'Das Wetter ist heute gut.',
    'Die Sonne scheint.',
    'Es regnet heute.',
    'Ich spiele gern Fußball.',
    'Ich kann gut schwimmen.',
    'Ich höre gern Musik.',
  ],
  writing: [
    { prompt: 'Describe today\'s weather in two sentences.', hint: 'Das Wetter ist... Es ist...' },
    { prompt: 'Write about your hobby and when you do it.', hint: 'Mein Hobby ist... Ich spiele/lese... am...' },
    { prompt: 'Say what you do in summer and in winter.', hint: 'Im Sommer... Im Winter...' },
  ],
};

const berlin: StageData = {
  cityName: 'Berlin', cityNameDe: 'Berlin', emoji: '🏛️',
  theme: 'Making Plans & Visiting the Capital',
  grammarNote: 'Plans: "Ich möchte... besuchen" (I would like to visit). Modal verbs push the second verb to the end: Wir wollen das Museum besuchen. Separable "einladen": Ich lade meine Freunde ein.',
  vocab: [
    { de: 'Hauptstadt', g: 'die', en: 'capital city', ex: 'Berlin ist die Hauptstadt von Deutschland.', exEn: 'Berlin is the capital of Germany.' },
    { de: 'Reise', g: 'die', en: 'trip / journey', ex: 'Die Reise nach Berlin ist lang.', exEn: 'The trip to Berlin is long.' },
    { de: 'reisen', en: 'to travel', ex: 'Wir reisen gern zusammen.', exEn: 'We like travelling together.' },
    { de: 'besuchen', en: 'to visit', ex: 'Ich möchte das Museum besuchen.', exEn: 'I would like to visit the museum.' },
    { de: 'treffen', en: 'to meet', ex: 'Wir treffen uns am Tor.', exEn: 'We meet at the gate.' },
    { de: 'vielleicht', en: 'maybe', ex: 'Vielleicht kommt er morgen.', exEn: 'Maybe he is coming tomorrow.' },
    { de: 'natürlich', en: 'of course', ex: 'Natürlich komme ich!', exEn: 'Of course I am coming!' },
    { de: 'wichtig', en: 'important', ex: 'Die Familie ist wichtig.', exEn: 'Family is important.' },
    { de: 'interessant', en: 'interesting', ex: 'Das Museum ist sehr interessant.', exEn: 'The museum is very interesting.' },
    { de: 'berühmt', en: 'famous', ex: 'Das Brandenburger Tor ist berühmt.', exEn: 'The Brandenburg Gate is famous.' },
    { de: 'neu', en: 'new', ex: 'Das Geschenk ist neu.', exEn: 'The present is new.' },
    { de: 'modern', en: 'modern', ex: 'Berlin ist eine moderne Stadt.', exEn: 'Berlin is a modern city.' },
    { de: 'Plan', g: 'der', en: 'plan', ex: 'Der Plan ist gut.', exEn: 'The plan is good.' },
    { de: 'planen', en: 'to plan', ex: 'Wir planen eine Reise.', exEn: 'We are planning a trip.' },
    { de: 'Party', g: 'die', en: 'party', ex: 'Die Party ist am Samstag.', exEn: 'The party is on Saturday.' },
    { de: 'feiern', en: 'to celebrate', ex: 'Wir feiern meinen Geburtstag.', exEn: 'We are celebrating my birthday.' },
    { de: 'Geburtstag', g: 'der', en: 'birthday', ex: 'Mein Geburtstag ist im Mai.', exEn: 'My birthday is in May.' },
    { de: 'Geschenk', g: 'das', en: 'present / gift', ex: 'Das Geschenk ist für dich.', exEn: 'The present is for you.' },
    { de: 'einladen', en: 'to invite', ex: 'Ich möchte dich einladen.', exEn: 'I would like to invite you.' },
    { de: 'Tor', g: 'das', en: 'gate', ex: 'Das Tor ist sehr alt.', exEn: 'The gate is very old.' },
    { de: 'Mauer', g: 'die', en: 'wall', ex: 'Die Mauer ist Geschichte.', exEn: 'The wall is history.' },
    { de: 'kennen', en: 'to know (someone/something)', ex: 'Ich kenne Berlin gut.', exEn: 'I know Berlin well.' },
    { de: 'zeigen', en: 'to show', ex: 'Kannst du mir die Stadt zeigen?', exEn: 'Can you show me the city?' },
    { de: 'zusammen', en: 'together', ex: 'Wir reisen zusammen nach Berlin.', exEn: 'We travel to Berlin together.' },
  ],
  grammar: [
    { en: 'Berlin is the capital of Germany', de: 'Berlin ist die Hauptstadt von Deutschland' },
    { en: 'We are planning a trip', de: 'Wir planen eine Reise' },
    { en: 'Maybe we will meet tomorrow', de: 'Vielleicht treffen wir uns morgen' },
    { en: 'I want to visit the museum', de: 'Ich möchte das Museum besuchen' },
    { en: 'The party is on Saturday', de: 'Die Party ist am Samstag' },
    { en: 'I am inviting my friends', de: 'Ich lade meine Freunde ein' },
    { en: 'Of course I am coming', de: 'Natürlich komme ich' },
    { en: 'The Brandenburg Gate is famous', de: 'Das Brandenburger Tor ist berühmt' },
  ],
  errors: [
    { bad: 'Berlin ist der Hauptstadt.', wrong: 'der', right: 'die' },
    { bad: 'Wir plant eine Reise.', wrong: 'plant', right: 'planen' },
    { bad: 'Ich möchte das Museum besuchst.', wrong: 'besuchst', right: 'besuchen' },
    { bad: 'Ich lade meine Freunde aus.', wrong: 'aus', right: 'ein' },
  ],
  reading: {
    passage: 'Anna und Max planen eine Reise nach Berlin. Berlin ist die Hauptstadt von Deutschland und sehr modern. Sie möchten das Brandenburger Tor sehen — es ist berühmt. Max kennt ein interessantes Museum. Am Samstag ist eine Party: Annas Freundin feiert ihren Geburtstag. Anna kauft ein Geschenk. Die Reise wird schön!',
    qs: [
      { q: 'Where are Anna and Max travelling?', options: ['nach Berlin', 'nach Hamburg', 'nach Köln'], a: 'nach Berlin' },
      { q: 'What do they want to see?', options: ['das Brandenburger Tor', 'den Dom', 'das Meer'], a: 'das Brandenburger Tor' },
      { q: 'What does Max know?', options: ['ein interessantes Museum', 'ein gutes Restaurant', 'einen schönen Park'], a: 'ein interessantes Museum' },
      { q: 'What happens on Saturday?', options: ['eine Party', 'ein Fußballspiel', 'ein Konzert'], a: 'eine Party' },
      { q: 'What does Anna buy?', options: ['ein Geschenk', 'ein Ticket', 'ein Buch'], a: 'ein Geschenk' },
    ],
  },
  speaking: [
    'Berlin ist die Hauptstadt von Deutschland.',
    'Wir planen eine Reise.',
    'Ich möchte das Museum besuchen.',
    'Natürlich komme ich!',
    'Herzlichen Glückwunsch zum Geburtstag!',
    'Kannst du mir die Stadt zeigen?',
  ],
  writing: [
    { prompt: 'Plan a trip: where you are going, what you want to visit, who is coming.', hint: 'Wir reisen nach... Ich möchte... besuchen. ... kommt zusammen mit...' },
    { prompt: 'Invite a friend to your birthday party.', hint: 'Ich lade dich ein... Die Party ist am...' },
    { prompt: 'Write two sentences about Berlin.', hint: 'Berlin ist... Das Brandenburger Tor...' },
  ],
};

export const A1_STAGES: StageData[] = [koeln, frankfurt, stuttgart, muenchen, duesseldorf, hannover, hamburg, berlin];
